name: personnummer
version: 3.0.4
description: Validate Swedish personal identity numbers with Dart and Flutter.
homepage: https://github.com/personnummer/dart

environment:
  sdk: ">=2.0.0 <3.0.0"

dev_dependencies:
  test: ^1.17.12
